### ISSUE TITLE
not work !!!

### ISSUE THREAD

**Issue by todokku** [Pycomet/PromotionBot#1]
Hi Codefred ,
please make some details about variables bellow , find in spam.py line 15,16 , 
targetGrp = ''
user = ''
& what  diffrent kind of types of logins with phone or bot tokken in consule 
i also try both methods & after send spam comment in telegram bot , show me bellow
cannot cast input peer chat to any kind of input peer channel
waiting for your response dude,
finest regards
goodbye

**Comment by Pycomet-zz** [comment]
Thank you for using my python script. I will add comment to line 15 and 16
to indicate what does variables represent. What are the methods
you attempted using that gave you errors?

**Comment by todokku** [comment]
hi pycomet , 
im trying both login via bot tokken & login via phone number & in both login methods getting same error after put comment in telegram bot section ,
please note your worked flow to follow your solution
waiting for your response dude,
finest regards
goodbye

**Comment by Pycomet-zz** [comment]
The "cannot cast input peer chat to any kind of input peer channel" error is as a result of you using a bot token as the login method.

I suggest you use the phone number of an existing account to run the application. As I have tested that to run smoothly. Please let me know when you have it running on your local machine and any idea on how I could improve the source code.

Thank you
